name: share_plus_platform_interface
description: A common platform interface for the share_plus plugin.
version: 3.2.1
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

dependencies:
  cross_file: ^0.3.3+2
  flutter:
    sdk: flutter
  meta: ^1.7.0
  mime: ^1.0.2
  plugin_platform_interface: ^2.0.0
  path_provider: ^2.0.11
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  flutter_lints: ^2.0.1
  test: ^1.21.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"
