name: emoji_proposal
description: Propose emojis based a human-made text using NLP.
version: 0.0.1
homepage: https://gitlab.com/TheOneWithTheBraid/emoji_proposal/
repository: https://gitlab.com/TheOneWithTheBraid/emoji_proposal.git
issue_tracker: https://gitlab.com/TheOneWithTheBraid/emoji_proposal/-/issues/

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  emojis: ^0.9.9
  sentiment_dart: ^0.0.5

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^2.0.0
  test: ^1.20.1
