name: xml
version: 6.3.0

description: A lightweight library for parsing, traversing, querying, transforming and building XML documents.
homepage: https://github.com/renggli/dart-xml

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  collection: ^1.17.0
  meta: ^1.9.0
  petitparser: ^5.4.0
dev_dependencies:
  args: ^2.4.0
  lints: ^2.0.0
  test: ^1.24.0