name: enhanced_enum
description: Add fancy methods to your enums
version: 0.2.4
homepage: https://famedly.com
repository: https://gitlab.com/famedly/company/frontend/libraries/enhanced_enum/
issues: https://gitlab.com/famedly/company/frontend/libraries/enhanced_enum/-/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.4
  import_sorter: ^4.6.0
  lints: ^2.0.0
