include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - empty_constructor_bodies
    - one_member_abstracts

analyzer:
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    todo: info
