name: image
version: 4.3.0
description: >-
  Dart Image Library provides server and web apps the ability to load, manipulate,
  and save images with various image file formats.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/blob/main/doc/README.md

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  meta: ^1.3.0
  xml: ^6.0.1

dev_dependencies:
  build_runner: ^2.1.5
  build_test: ^2.1.4
  build_web_compilers: ^4.0.5
  http: ^1.1.0
  lints: ^2.0.1
  test: ^1.16.0
