name: unifiedpush
description: Push notifications with the provider chosen by the user.
version: 4.0.3
homepage: "https://unifiedpush.org/developers/flutter"
documentation: "https://unifiedpush.org/developers/flutter"
repository: https://github.com/UnifiedPush/flutter-connector
issue_tracker: https://github.com/UnifiedPush/flutter-connector/issues

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  unifiedpush_platform_interface: ^1.0.0
  unifiedpush_android: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: unifiedpush_android

#todev#dependency_overrides:
#todev#  unifiedpush_platform_interface:
#todev#    path: ../unifiedpush_platform_interface
#todev#  unifiedpush_android:
#todev#    path: ../unifiedpush_android
