name: highlighter
description: Syntax highlighting for Dart with lots of languages and themes support.
version: 0.1.1
homepage: https://github.com/predatorx7/highlight

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.5
  path: ^1.8.0
