name: emojis
description: Emojis for Dart! This package contain all unicode 13.0 emojis (2020)!
version: 0.9.9
author: Naji <teamnaji@gmail.com>
homepage:  https://github.com/i-Naji/emojis

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.19.3
  pedantic: ^1.11.1
