# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

name: olm
description: Dart bindings for Olm, an implementation of the olm and megolm cryptographic ratchets
version: 2.0.3
homepage: https://famedly.gitlab.io/libraries/dart-olm/
repository: https://gitlab.com/famedly/libraries/dart-olm

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  js: ^0.6.4
  ffi: ^2.0.0

dev_dependencies:
  coverage: ^1.0.1
  dart_code_metrics: ^4.17.1
  import_sorter: ^4.6.0
  test: ^1.21.4
