include: package:lints/recommended.yaml

linter:
  rules:
    avoid_unused_constructor_parameters: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    provide_deprecation_message: false